# -*- coding: utf-8 -*-
"""BUSQUEDA SECUENCIAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UbPOtD4m9AILuuVz2SLgktNJNuU4k14u
"""

edades = [20, 15, 18, 22, 19, 18]
buscado = int(input("Ingrese la edad a buscar: "))
encontrado = False

for i in range(len(edades)):
    if edades[i] == buscado:
        print(f"Encontrado en la posición {i}")
        encontrado = True

if not encontrado:
    print("No se encontró la edad.")