# -*- coding: utf-8 -*-
"""IMPRESION DE ARREGLO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2e7EXM-h6AckQ1f1d7XSr8-u-FaHGc0
"""

edades = [18, 25, 32, 45, 12]

print("Listado de edades:")
print("-" * 18) # Truco de Python: repite el guion 18 veces

for edad in edades:
    print(f"- {edad} años")