# -*- coding: utf-8 -*-
"""MODIFICACION DE UN ELEMENTO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FftSrRP64AYmKCGmLnYfp69YO-FsgQs
"""

edades = [12, 18, 22, 35, 40]


pos = int(input("Ingrese la posición a modificar (0-4): "))


if 0 <= pos < len(edades):
    nuevo = int(input("Ingrese el nuevo valor: "))
    edades[pos] = nuevo
    print(f"Lista actualizada: {edades}")
else:
    print("Error: Esa posición no existe.")