# -*- coding: utf-8 -*-
"""REGISTRO DE DATOS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0CMEn79etPyr1JUxFmnM6EWveVZQEnA
"""

edades = [0] * 5

for i in range(len(edades)):
    edades[i] = int(input(f"Ingrese edad {i+1}: "))